name: Integrate (backend)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:

  code-format:
    name: Code format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          working-directory: backend
      - name: Run Pint
        run: vendor/bin/pint --test


  test:
    name: Test (PHP ${{ matrix.php }} - ${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
        driver: [ 'sqlite', 'mysql', 'postgres' ]
        include: 
          - driver: 'mysql'
            name: MySQL
            host: '127.0.0.1'
            port: 3307
            database: 'staffkit'
          - driver: 'postgres'
            name: PostgreSQL
            host: '127.0.0.1'
            port: 5433
            database: 'staffkit'
          - driver: 'sqlite'
            name: SQLite
            database: ':memory:'
    services:
      postgres:
        image: ${{ matrix.driver == 'postgres' && 'postgres:16.3' || '' }}
        env:
          POSTGRES_USER: staffkit
          POSTGRES_PASSWORD: staffkit
          POSTGRES_DB: staffkit
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
      mysql:
        image: ${{ matrix.driver == 'mysql' && 'mysql:9.0' || '' }}
        env:
          MYSQL_ROOT_PASSWORD: staffkit
          MYSQL_DATABASE: staffkit
          MYSQL_USER: staffkit
          MYSQL_PASSWORD: staffkit
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3307:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          working-directory: backend
      - name: Run tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: ${{ matrix.driver }}
          DB_HOST: ${{ matrix.host }}
          DB_PORT: ${{ matrix.port }}
          DB_DATABASE: ${{ matrix.database }}
          DB_USERNAME: staffkit
          DB_PASSWORD: staffkit