name: Integrate (backend)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        uses: ramsey/composer-install@v3
      - name: Run tests
        run: vendor/bin/phpunit